apiVersion: apps/v1
kind: Deployment
metadata:
  name: cardbot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cardbot
  template:
    metadata:
      labels:
        app: cardbot
    spec:
      containers:
        - name: cardbot
          image: cardbot:latest
          imagePullPolicy: Never
          resources:
            requests:
              memory: 16Mi
              cpu: 200m
            limits:
              memory: 512Mi
              cpu: 200m
          ports:
            - name: http
              containerPort: 3978
---
apiVersion: v1
kind: Service
metadata:
  name: cardbot
spec:
  type: NodePort
  selector:
    app: cardbot
  ports:
    - name: http
      port: 80
      targetPort: http
